version: '3.7'
services:
  social_app:
    container_name: social_app
    ports:
      - '3000:3000'
    build:
      context: social-app
      dockerfile: Dockerfile
    volumes:
      - ./social-app:/app
      - /app/node_modules
      - /app/.next
